### ISSUE TITLE
Use the core tools

### ISSUE THREAD

**Issue by brianteeman** [Jensen-Technologies/phpstorm-meta-joomla#1]
Better to use the provided core tools instead of reinventing the wheel which is already round ;)

https://github.com/joomla/joomla-cms/blob/staging/build/stubGenerator.php

**Comment by v-escobar** [comment]
@brianteeman we would update the file from time to time but it would take us more time to download Joomla! repository and run that command. We are not reinventing the wheel, we just have published what that script generates.

**Comment by brianteeman** [comment]
ycfs
